apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: weather-api
  description: Provides weather forecast data for a given city
  tags:
    - openapi
spec:
  type: openapi
  lifecycle: experimental
  owner: platform-team
  system: weather-system
  definition:
    $openapi: https://raw.githubusercontent.com/your-org/your-repo/main/openapi.yaml
