apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  annotations:
    github.com/project-slug: Sathishkunisai/backstage
spec:
  type: openapi
  lifecycle: experimental
  owner: platform-team
  definition:
    $openapi: https://raw.githubusercontent.com/Sathishkunisai/backstage/main/openapi-1.yaml
