apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: deploy-azure
  title: Provision Azure Infrastructure
  description: Create an Azure VM, Storage, and Networking via Terraform
spec:
  owner: cloud-team
  parameters:
    - title: Azure Configuration
      required: [resource_group, vm_name, region]
      properties:
        resource_group:
          type: string
          title: Resource Group
        vm_name:
          type: string
          title: VM Name
        region:
          type: string
          title: Region
          default: eastus
  steps:
    - id: fetch
      name: Fetch Terraform Template
      action: fetch:template
      input:
        url: ./skeleton
    - id: terraform
      name: Apply Terraform
      action: run:script
      input:
        script: |
          cd ./skeleton
          terraform init
          terraform apply -auto-approve \
            -var "resource_group=${{ parameters.resource_group }}" \
            -var "vm_name=${{ parameters.vm_name }}" \
            -var "region=${{ parameters.region }}"
  output:
    text:
      - title: VM Info
        content: 'Azure VM ${{ parameters.vm_name }} deployed in ${{ parameters.region }}'