apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-test-template
  title: Simple Component Registration Test
  description: Creates a minimal component entry in the Backstage Catalog.
spec:
  owner: user
  type: service
  parameters:
    - title: Component Details
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Component ID
          type: string
          description: Unique ID for the new component.
        owner:
          title: Component Owner
          type: string
          description: The owner of this component (e.g., 'team-a' or 'user').
          default: user
  steps:
    - id: fetch-base
      name: Fetch Base Content
      action: fetch:plain
      input:
        targetPath: ./
        files:
          - src: ./skeleton/catalog-info.yaml
            target: ./catalog-info.yaml
    
    - id: register
      name: Register Component
      action: catalog:register
      input:
        catalogInfoUrl: ./catalog-info.yaml
    
  output:
    links:
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}