apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: deploy-azure
  title: Provision Azure Infrastructure
  description: Create an Azure VM, Storage, and Networking via Terraform
spec:
  owner: cloud-team
  parameters:
    # ... (parameters block remains the same)
    - title: Azure Configuration
      required: [resource_group, vm_name, region]
      properties:
        # ... (properties details)
  steps:
    - id: fetch
      name: Fetch Terraform Template
      action: fetch:template
      input:
        url: ./skeleton
    - id: terraform
      name: Apply Terraform
      action: run:script
      input:
        script: |
          cd ./skeleton
          terraform init
          terraform apply -auto-approve \
            -var "resource_group=${{ parameters.resource_group }}" \
            -var "vm_name=${{ parameters.vm_name }}" \
            -var "region=${{ parameters.region }}"
    - id: publish-catalog # <--- NEW STEP ADDED
      name: Publish to Backstage Catalog
      action: catalog:register
      input:
        catalogInfoUrl: ./skeleton/catalog-info.yaml
  output:
    # ... (output block remains the same)
